name: Tests


on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Test
        uses: fylein/python-pytest-github-action@v1
        with:
          args: pytest run_tests.py
